let music = {
    "#Special": {
        "Beg 17:50": "EcNNijfPHOo",
        "Ph1 9:44": "-k3XXGmu-dw",
        "Ph2 15:11": "Fq4DwRwBw6A",
        "Gwyn": "mLBybw-IJ5U",
        "Yhorm": "M_XpSjqWaS4",
    },
    "WoW": {
        "Undercity": "WaG9K6Agx-0",
        "Arathi H.": "rFek5w7tDI0",
        "Frostfire": "EpHlONJwLa8",
        "Gorgrond": "61biu9jhDxs",
        "Highmaul": "PIhcPcvNPDs",
        "Townlong": "pFy9i3niIig",
        "Karazhan": "jrYxp3OuB1s",
        "Darkmoon": "a2FUqpDdvH8",
        "HordeTav": "HrvA2eAHcJ4",
        "Caverns": "OMRI8tY_uuk",
        "Ironforge": "aFbCofgwdXo",
        "Kun-Lai": "FIeql1dS2GM",
        "Tiragarde": "M-9DXlyCFkw",
        "Ulduar": "EpQSBmsj5L4",
        "Val 4Wind": "50EOOzhovjg",
        "Argus": "3pR4Z6grAI8",
        "Ashenvale": "xTPn_Nk_KrM",
        "Bloodmyst": "XcQri_b6q9A",
        "Darkshore": "5VhP28vOl74",
        "Elwynn F.": "MW4fASDkQXA",
        "Eversong": "FU_yNE2MMOU",
        "Feralas": "LwMic-KXQlY",
        "Ghostland": "HKnBT3sWUjg",
        "Spires": "RttCWIwq46o",
        "StormPeaks": "C9IXUwqxIao",
        "Stormheim": "yKTOZ47PK08",
        "Strangleth": "Gli5allDOa8",
        "Teldrassil": "BV-v9bdMQp0",
        "Val'sharah": "yHYUvPyKG0o",
        "Vashj-ir": "7SC9bX3BeGI",
        "Zangarmars": "f-Ic9feSwcg",
        "Crystalson": "wG_0NevdvzI",
        "Exodar": "pXseyytvgkg",
        "Moonglade": "rbM0eGQepgc",
        "Suramar": "ACgoXvkhlPE",
        "AhnQiraj": "HOdFlmnyaTQ",
        "AzjolNeru": "Q5xGd9jwd6Q",
        "Azuremyst": "fwrflawejvE",
        "BlackTmp": "n3MCruu35Og",
        "Blackrock": "NC6RdsTvcuA",
        "BladesEd": "KrKlW_v-Ylk",
        "BoreanTu": "Lu1yIzqpUR4",
        "Deepholm": "kwLQH7NDCfw",
        "Dragonblig": "DTwwIKU82xE",
        "Duskwood": "jpb1nH2q_0k",
        "EasternPlg": "rGiwjDZfW5s",
        "Emerald": "Mtnt1lrXjhw",
        "Firelands": "kCoQV-xKenk",
        "Hellfire": "BafgaT1PS_A",
        "Icecrown": "SIkNWR6Y-CY",
        "IcecrownCit": "ne-JwpCXUbM",
        "Netherstorm": "uAwIBtov5EM",
        "Nexus": "tBUPA-g65jY",
        "Shadowm": "P3r_6wUHYIY",
        "Shattrath": "e15tpUhTMD8",
        "Silithus": "rzL9ZpnmSYU",
        "Silverpine": "tLeHkxSgPlk",
        "Tanaan": "XTVHJEHX_uY",
        "Tanaris": "ydrfcDTLS0Y",
        "Tirisfal": "oSF4keDUM5E",
        "Vol-dun": "NGuccBwxqAk",
        "WesternPlg": "7m0FDE2ggOA",
        "Wintersprg": "YDOp-IlsO6I",
        "Zul-Aman": "3VmF7pIuzMU",
        "Zul-Drak": "Sc5Oj1WgwwI",
        "Naxxramas": "VCLxvtccYIs",
        "Orgrimmar": "L_QA-ZUAOHk",
        "HowlFjord": "wjTe0R2bREY",
        "Dalaran": "BV7mKCgKhZY",
        "Sunwell": "BBaNoOsKaEM",
        "Barrens": "YONdeDeSgrQ",
        "Grizzly H.": "pWTSK5waNs8",
        "Mulgore": "q8PqlJBeuT0",
        "Nagrand": "4IrA6af0SJs",
        "Sholazar": "-3cSt5tW7YQ",
        "Thunder": "VRE1WjivRaU",
        "Wandering": "bAG2wmv3kwo",
        "Darnassus": "wLY-5S-6xuY",
        "Silvermoon": "bSwzMgZqcR4",
        "Talador": "IjrkRFZHOUs",
        "Wintergrsp": "x1d8O0E3i08",
        "Durotar": "ejqUoPoyUg8",
        "Nagrand": "0msy-ALryyw",
        "Uldum": "o4Xma-jmFNE",
        "Stormwind": "roMWEeV2P4U",
        "Highmount": "MvJ_uKiZxRk",
        "DunMorog": "YfMn7UfZzGc",
        "Westfall": "Z3O2r5K8e9A",
        "Azsuna": "cBWnjEC81fA",
        "Dalaran": "1hRjNoUl4WQ",
        "Jade For.": "nWcbYcU1eaQ",
        "Krasarang": "73B9a2EKlcM",
        "Redridge": "RUFJdHSQZrk",
        "ShadowmD": "LYy9Xk4Y_A8",
        "Skywall": "Ph45OfLPQME",
        "Tuskarr": "NwuJdxKkY0E",
        "Gilneas": "R8jsJQnKhMo",
        "AllianceT": "Oeo2VCCtUZQ",
        "Brewfest!": "1hcpg3104KA",
        "TavrnAzer": "3p8jLMz0lu8",
        "Argent T": "0pEd9xtsMvA",
        "Boralus": "K3hjVijzrtM",
        "Dazaralor": "7JMm6b-Zi_s",
        "Mechagon": "yMkbKZWDkqg",
    } 
};

let sources = Object.keys(music).sort();
let buttons = document.getElementById("buttons");
let template = document.querySelector('#musicset');

function change(newSrc, newID) {
    document.getElementById("film").innerHTML = '<iframe width="560" height="315" src="https://www.youtube.com/embed/' + music[newSrc][newID] + '" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
}

for(let src of sources) {
    let names = Object.keys(music[src]).sort();
    let div = template.content.cloneNode(true);
    let setbuttons = div.querySelector(".setbuttons");
    div.querySelector(".settitle > h2").innerHTML = src;
    for(let nam of names) {
        setbuttons.innerHTML += '<button onclick="change(\'' + src + '\', \'' + nam + '\')">' + nam + '</button>';
    }
    buttons.appendChild(div);
}
